[glyphs.italic.M]
leftSideBearing = 5

[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.IosevkaCustom.variants.design]
one = "no-base-long-top-serif"
two = "straight-neck-serifed"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "oblique-arched-serifless"
six = "straight-bar"
seven = "bend-serifless-crossbar"
eight = "crossing"
nine = "open-contour"
zero = "tall-slashed"
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-i = "serifed"
capital-j = "flat-hook-serifed"
capital-k = "curly-serifless"
capital-p = "open-serifed"
capital-q = "crossing"
capital-r = "straight-bottom-right-serifed"
capital-u = "tailed-serifless"
capital-v = "curly-serifed"
capital-w = "straight-serifed"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "straight-serifed-with-horizontal-crossbar"
a = "single-storey-tailed"
b = "toothless-rounded-serifed"
d = "tailed-serifed"
e = "rounded"
f = "flat-hook-tailed"
h = "tailed-serifless"
i = "tailed"
j = "serifless"
l = "tailed"
m = "earless-rounded-double-arch-short-leg-serifless"
n = "earless-corner-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-tailed-serifless"
r = "earless-corner-serifless"
s = "bilateral-inward-serifed"
u = "tailed-serifless"
v = "curly-motion-serifed"
w = "rounded-vertical-sides-serifless"
x = "curly-bilateral-motion-serifed"
y = "cursive-serifless"
z = "straight-serifless-with-horizontal-crossbar"
capital-gamma = "serifed"
lower-gamma = "casual"
capital-delta = "straight"
lower-delta = "flat-top"
capital-lambda = "straight-tri-serifed"
lower-lambda = "tailed-turn"
lower-pi = "tailed"
lower-tau = "tailed"
lower-phi = "straight"
lower-chi = "semi-chancery-curly-serifless"
lower-psi = "serifed"
punctuation-dot = "round"
braille-dot = "round"
tilde = "low"
asterisk = "turn-penta-low"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "upright"
ampersand = "upper-open"
at = "threefold"
dollar = "interrupted"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "corner"
pilcrow = "high"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

  [buildPlans.IosevkaCustom.ligations]
  inherits = "dlig"

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 8 
shape = "italic"
menu = "italic"
css = "italic"